### ISSUE TITLE
AMP stack pack should be AMP optimizer aware

### ISSUE THREAD

**Issue by igrigorik** [GoogleChrome/lighthouse-stack-packs#20]
AMP caches (e.g. Google AMP Cache) apply optimizations on top of the AMP content they ingest, which can also be run locally via [amp optimizer](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer). We should..

(a) Recommend use of amp optimizer in audits that may be affected by its absence, or (b) perhaps detect and flag its absence as a top level recommendation?

@sebastianbenz @pbakaus

**Comment by housseindjirdeh** [comment]
PR #32 by @sebastianbenz takes care of (a)! (recommends amp-optimizer to avoid render blocking resources)
