### ISSUE TITLE
Illegal formatting in AMP stack pack

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse-stack-packs#27]
Having `code-spans` inside a `[link]()` will not render properly in Lighthouse.

```
...use [`amp-anim`](https://www.ampproject.org/docs/reference/components/amp-anim) to minimize...",
```
```
...the [`amp-font`](https://www.ampproject.org/docs/reference/components/amp-font#on-load-add-class) component..."
```

I support this being added as a feature in our i18n parser, but this syntax won't work in the current status quo.

**Comment by housseindjirdeh** [comment]
Ah cheers, didn't know that wasn't supported!

Fixed :
