### ISSUE TITLE
Drupal Stack pack

### ISSUE THREAD

**Issue by hestenet** [GoogleChrome/lighthouse-stack-packs#28]
Starting a stub issue here at the Google CMS Leadership summit for exploring a stack pack for Drupal. 

One of the concerns for Drupal as a project is Drupal is not an opinionated CMS out of the box. Different use cases on top of Drupal might have very different audit requirements and recommendations. 

Before we could move forward further we’d need to understand the right architectural approach for handling this variance.

**Comment by housseindjirdeh** [comment]
Thanks a ton for opening this! Quite a few people have already asked about Drupal support so I'm glad to see the discussion starting :)

> Different use cases on top of Drupal might have very different audit requirements and recommendations

Forgive me for my limited experience with Drupal - but some thoughts:

- For most of the performance audits to begin with, would it be possible to come up with high-level enough suggestions that could work for most use-cases?
- Would it be possible/worthwhile to target a specific Drupal version to begin with? Definitely not what we're aiming to do just yet for any stack, but I wonder if different versions/use-cases are so different that this should be considered.

Will love to keep the discussion rolling 💬

**Comment by housseindjirdeh** [comment]
We have a first draft for a Drupal pack #41!
