### ISSUE TITLE
Typo in magento

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse-stack-packs#35]
https://github.com/GoogleChrome/lighthouse-stack-packs/blob/master/packs/magento.json#L8

> Use [Terser](https://www.npmjs.com/package/terser) to minify all JavaScript assets outfrom from static content deployment, and disable the built-in minification feature.

should be something like:

> Use [Terser](https://www.npmjs.com/package/terser) to minify all JavaScript assets from static content deployment, and disable the built-in minification feature.

**Comment by brendankenny** [comment]
fixed in #36
